"""Deny shims (SPEC §5): make commands like ``xcodebuild`` unusable for agents.

The scheduler puts ``$TASKGRAPH_STATE/shims`` first on the agents' ``PATH`` and
creates one executable per ``agent.deny`` entry there.  Each shim only runs the
real binary — resolved to an absolute path *at creation time*, skipping the shim
directory itself so an old shim can never shadow the real command — when
``TASKGRAPH_LEASE`` is set (i.e. inside ``taskgraph lease``).  Otherwise it
prints how to run the command through the project's lease wrapper and exits 64.

That is the "shims" half of SPEC §5: agents cannot bypass the shared-resource
semaphore by calling the tool directly; the shim lives outside every worktree,
so agents cannot edit it either.
"""

from __future__ import annotations

import os
import re
import shutil
import tempfile
from pathlib import Path
from typing import Iterable

from .lease import LEASE_ENV, state_root

#: Exit status of a denied command (EX_USAGE).
DENIED_EXIT = 64

#: First-line-ish marker identifying shims taskgraph generated (vs. foreign files).
MARKER = "# Generated by taskgraph"

SHIM_DIRNAME = "shims"

# Deny entries are bare command names; paths/metacharacters cannot be shadowed.
_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._+-]*$")


class ShimsError(Exception):
    """A deny shim cannot be created (bad command name, unwritable state dir)."""


def shim_dir(root: Path | str | None = None) -> Path:
    """Return the directory holding the generated shims."""
    return (Path(root) if root is not None else state_root()) / SHIM_DIRNAME


def denial_message(cmd: str, resource: str | None = None) -> str:
    """The message a shim prints when ``TASKGRAPH_LEASE`` is not set."""
    shared = f"the shared {resource}" if resource else "the shared resource"
    return (
        f"{cmd} is disabled for agents: run it through the project's lease "
        f"wrapper (e.g. ./dev.sh) — it waits for {shared}"
    )


def shim_script(cmd: str, real: str, resource: str | None = None) -> str:
    """Render the ``sh`` script for one command, executing ``real`` when leased."""
    return (
        "#!/bin/sh\n"
        f"{MARKER} (SPEC §5) — deny shim for '{cmd}'; do not edit.\n"
        f'if [ -z "${{{LEASE_ENV}:-}}" ]; then\n'
        f"    echo {_sh_quote(denial_message(cmd, resource))} >&2\n"
        f"    exit {DENIED_EXIT}\n"
        "fi\n"
        f'exec {_sh_quote(real)} "$@"\n'
    )


def real_command(cmd: str, shims: Path | str | None = None, path: str | None = None) -> str | None:
    """Resolve ``cmd`` on ``PATH`` (default ``$PATH``), skipping the shim dir.

    Returns an absolute, symlink-resolved path, or ``None`` when the command
    does not exist outside the shims (a shim must never exec itself).
    """
    directory = Path(shims) if shims is not None else shim_dir()
    search = os.environ.get("PATH", os.defpath) if path is None else path
    entries = [p for p in search.split(os.pathsep) if p and not _same_path(p, directory)]
    found = shutil.which(cmd, path=os.pathsep.join(entries))
    return os.path.realpath(found) if found else None


def path_with_shims(base: str | None = None, root: Path | str | None = None) -> str:
    """Return ``base`` (default ``$PATH``) with the shim dir first and unique.

    Callers must *export* this PATH (SPEC §5: a shell-local PATH never reached
    the agents' child shells).
    """
    directory = shim_dir(root)
    search = os.environ.get("PATH", os.defpath) if base is None else base
    rest = [p for p in search.split(os.pathsep) if p and not _same_path(p, directory)]
    return os.pathsep.join([os.fspath(directory), *rest])


def create_shims(
    commands: Iterable[str],
    resource: str | None = None,
    root: Path | str | None = None,
    path: str | None = None,
) -> dict[str, Path]:
    """Install a shim for every command in ``commands``; return ``{command: path}``.

    Commands that cannot be resolved outside the shim dir are skipped, and
    previously generated shims whose command is no longer denied are removed
    (so ``agent.deny`` stays the single source of truth).  ``resource`` is only
    used to name the shared resource in the denial message.
    """
    directory = shim_dir(root)
    directory.mkdir(parents=True, exist_ok=True)
    created: dict[str, Path] = {}
    for name in dict.fromkeys(commands):  # dedupe, keep plan order
        _check_name(name)
        real = real_command(name, directory, path)
        if real is None:
            continue
        target = directory / name
        _write_atomic(target, shim_script(name, real, resource))
        created[name] = target
    _prune(directory, set(created))
    return created


# ------------------------------------------------------------------------- internals


def _check_name(name: str) -> None:
    if not _NAME_RE.match(name):
        raise ShimsError(f"agent.deny: {name!r} is not a bare command name")


def _same_path(a: os.PathLike | str, b: os.PathLike | str) -> bool:
    return os.path.realpath(os.path.abspath(a)) == os.path.realpath(os.path.abspath(b))


def _sh_quote(text: str) -> str:
    return "'" + text.replace("'", "'\\''") + "'"


def _write_atomic(target: Path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=f".{target.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.chmod(tmp, 0o755)
        os.replace(tmp, target)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def _prune(directory: Path, keep: set[str]) -> None:
    """Best-effort removal of generated shims (and temp files) no longer wanted."""
    try:
        entries = sorted(directory.iterdir())
    except OSError:
        return
    for entry in entries:
        if entry.name in keep or not entry.is_file():
            continue
        try:
            with entry.open("r", encoding="utf-8", errors="replace") as handle:
                head = handle.readline() + handle.readline()
        except OSError:
            continue
        if MARKER in head:
            try:
                entry.unlink()
            except OSError:
                pass


__all__ = [
    "DENIED_EXIT",
    "LEASE_ENV",
    "MARKER",
    "ShimsError",
    "create_shims",
    "denial_message",
    "path_with_shims",
    "real_command",
    "shim_dir",
    "shim_script",
]
